# Generated by Django 4.2.8 on 2023-12-27 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0003_remove_forge_construction_started_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forge',
            name='constuction_started_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='goldmine',
            name='constuction_started_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='lumberjack',
            name='constuction_started_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='stonemine',
            name='constuction_started_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='storage',
            name='constuction_started_at',
            field=models.DateTimeField(null=True),
        ),
    ]
