# Generated by Django 4.2.8 on 2023-12-27 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0004_forge_constuction_started_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goldmine',
            old_name='constuction_started_at',
            new_name='construction_started_at',
        ),
        migrations.RenameField(
            model_name='lumberjack',
            old_name='constuction_started_at',
            new_name='construction_started_at',
        ),
        migrations.RenameField(
            model_name='stonemine',
            old_name='constuction_started_at',
            new_name='construction_started_at',
        ),
        migrations.RenameField(
            model_name='storage',
            old_name='constuction_started_at',
            new_name='construction_started_at',
        ),
        migrations.RemoveField(
            model_name='forge',
            name='constuction_started_at',
        ),
        migrations.AddField(
            model_name='forge',
            name='construction_started_at',
            field=models.DateTimeField(null=True),
        ),
    ]
