# Generated by Django 4.2.8 on 2023-12-27 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0006_barracks_church_citywall'),
    ]

    operations = [
        migrations.AddField(
            model_name='town',
            name='barracks',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='building.barracks'),
        ),
        migrations.AddField(
            model_name='town',
            name='church',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='building.church'),
        ),
        migrations.AddField(
            model_name='town',
            name='cityWall',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='building.citywall'),
        ),
    ]
