# Generated by Django 4.2.8 on 2023-12-27 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0007_town_barracks_town_church_town_citywall'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(default=0)),
                ('under_construction', models.BooleanField(default=False)),
                ('construction_started_at', models.DateTimeField(null=True)),
                ('construction_finished_at', models.DateTimeField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
