# Generated by Django 4.2.8 on 2023-12-27 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0008_farm'),
    ]

    operations = [
        migrations.AddField(
            model_name='town',
            name='farm',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='building.farm'),
        ),
    ]
