# Generated by Django 4.2.8 on 2023-12-29 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0009_town_farm'),
    ]

    operations = [
        migrations.AddField(
            model_name='forge',
            name='multiplier',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='goldmine',
            name='multiplier',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='lumberjack',
            name='multiplier',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='stonemine',
            name='multiplier',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
