# Generated by Django 4.2.8 on 2023-12-29 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0010_forge_multiplier_goldmine_multiplier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forge',
            name='multiplier',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='goldmine',
            name='multiplier',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='lumberjack',
            name='multiplier',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='stonemine',
            name='multiplier',
            field=models.FloatField(default=1),
        ),
    ]
