# Generated by Django 4.2.8 on 2023-12-29 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0011_alter_forge_multiplier_alter_goldmine_multiplier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='barracks',
            name='archer',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='barracks',
            name='javelin_thrower',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='barracks',
            name='swordsman',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
