# Generated by Django 4.1.7 on 2023-02-21 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Forge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(default=0)),
                ('under_construction', models.BooleanField(default=False)),
                ('construction_started_at', models.DateTimeField(null=True)),
                ('construction_finished_at', models.DateTimeField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GoldMine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(default=0)),
                ('under_construction', models.BooleanField(default=False)),
                ('construction_started_at', models.DateTimeField(null=True)),
                ('construction_finished_at', models.DateTimeField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lumberjack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(default=0)),
                ('under_construction', models.BooleanField(default=False)),
                ('construction_started_at', models.DateTimeField(null=True)),
                ('construction_finished_at', models.DateTimeField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StoneMine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(default=0)),
                ('under_construction', models.BooleanField(default=False)),
                ('construction_started_at', models.DateTimeField(null=True)),
                ('construction_finished_at', models.DateTimeField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(default=0)),
                ('under_construction', models.BooleanField(default=False)),
                ('construction_started_at', models.DateTimeField(null=True)),
                ('construction_finished_at', models.DateTimeField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Meine Stadt', max_length=24)),
                ('wood', models.PositiveIntegerField(default=0)),
                ('stone', models.PositiveIntegerField(default=0)),
                ('gold', models.PositiveIntegerField(default=0)),
                ('tools', models.PositiveIntegerField(default=0)),
                ('capacity', models.PositiveIntegerField(default=300)),
                ('forge', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='building.forge')),
                ('goldMine', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='building.goldmine')),
                ('lumberjack', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='building.lumberjack')),
                ('stoneMine', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='building.stonemine')),
                ('storage', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='building.storage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
