# Generated by Django 4.1.7 on 2023-02-21 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='town',
            name='capacity',
            field=models.FloatField(default=300),
        ),
        migrations.AlterField(
            model_name='town',
            name='gold',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='town',
            name='stone',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='town',
            name='tools',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='town',
            name='wood',
            field=models.FloatField(default=0),
        ),
    ]
