# Generated by Django 4.1.7 on 2023-02-21 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0002_alter_town_capacity_alter_town_gold_alter_town_stone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forge',
            name='construction_started_at',
        ),
        migrations.RemoveField(
            model_name='goldmine',
            name='construction_started_at',
        ),
        migrations.RemoveField(
            model_name='lumberjack',
            name='construction_started_at',
        ),
        migrations.RemoveField(
            model_name='stonemine',
            name='construction_started_at',
        ),
        migrations.RemoveField(
            model_name='storage',
            name='construction_started_at',
        ),
        migrations.AlterField(
            model_name='town',
            name='capacity',
            field=models.IntegerField(default=300),
        ),
    ]
